######################################################################
# Automatically generated by qmake (3.0) Wed Mar 23 18:00:32 2016
######################################################################

TEMPLATE = app
TARGET = compositor

### make path to qnxcompositor lib absolute or so
INCLUDEPATH += . ../../src

LIBS += -L../../src -lqnxcompositor

# Input
SOURCES += main.cpp \
    samplecompositor.cpp

HEADERS += \
    samplecompositor.h
