######################################################################
# Automatically generated by qmake (3.0) Wed Mar 23 21:45:24 2016
######################################################################

TEMPLATE = lib
TARGET = qnxcompositor
INCLUDEPATH += .

# Input
HEADERS += qnxcompositor.h
SOURCES += qnxcompositor.cpp
